import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const handleSubmit = async e => {
    e.preventDefault()
    const response = await fetch('/api/test', {
      method: 'POST',
      headers: {
        'Content-type': 'application/json'
      },
    })
    if (response.ok) {
      console.log('SUCCESS');
    }
    else {
      console.log('MAILING_ERROR');
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={e => handleSubmit(e)}>
        <button>
          TEST
        </button>
      </form>
    </>
  )
}
